name: turuke_app
description: "An app for small-scale poultry farmers to manage their flocks with ease"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pin_code_fields: ^8.0.0
  fl_chart: ^0.68.0
  provider: ^6.0.0
  http: ^1.0.0
  sqflite: ^2.0.0
  shared_preferences: ^2.0.0
  path_provider: ^2.0.0
  logger: ^2.5.0
  uuid: ^4.4.2
  flutter_launcher_icons: "^0.14.3"
  intl: ^0.20.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/big-chicken.png"
  web:
    generate: true